###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    memcached:
      image: memcached:alpine
      container_name: restfullbase-memcached

    mailhog:
      image: mailhog/mailhog:latest
      container_name: restfullbase-mailhog
      ports:
        - "2000:8025"

    mysql:
      image: mysql:8.0
      container_name: restfullbase-mysql
      restart: always
      command: '--default-authentication-plugin=mysql_native_password'
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root@123
        - MYSQL_DATABASE=db_app
        - MYSQL_USER=user_app
        - MYSQL_PASSWORD=pass_app
      ports:
        - "2001:3306"

    webserver:
      image: nginx:alpine
      container_name: restfullbase-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "1999:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: restfullbase-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

    adminer:
      image: adminer
      restart: always
      ports:
        - 2003:8080

